// @ts-check
const eslint = require('@eslint/js');
const { defineConfig } = require('eslint/config');
const tseslint = require('typescript-eslint');
const angular = require('angular-eslint');

module.exports = defineConfig([
  {
    // Auto-generated by openapi-typescript-codegen (see package.json's
    // "generate:api" script) — not handwritten, so it isn't linted.
    ignores: ['src/app/core/api-client/**'],
  },
  {
    files: ['**/*.ts'],
    extends: [
      eslint.configs.recommended,
      tseslint.configs.recommended,
      tseslint.configs.stylistic,
      angular.configs.tsRecommended,
    ],
    processor: angular.processInlineTemplates,
    rules: {
      // Off, not the prefix check alone: the schema requires a "style" (camelCase/
      // kebab-case), but the codebase's existing components (Nimbus-root,
      // Nimbus-user-by-mail, ...) intentionally use the capitalized "Nimbus"
      // prefix, which neither style option can express without renaming them.
      '@angular-eslint/directive-selector': 'off',
      '@angular-eslint/component-selector': 'off',
    },
  },
  {
    files: ['**/*.html'],
    extends: [angular.configs.templateRecommended, angular.configs.templateAccessibility],
    rules: {},
  },
]);
